version: '3.8'

services:
  patient-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: aditya
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  patient-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/patientdb
      SPRING_DATASOURCE_USERNAME: aditya
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - patient-db

volumes:
  pgdata:
