spring.application.name=patient-service

# PostgreSQL Config
# spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
# spring.datasource.username=aditya
# spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port=8000
